arch/x86: Unbreak df21bf37518b ("arch/x86: Provide the CPU number in the wakeup AP callback")
The commit df21bf37518b ("arch/x86: Provide the CPU number in the wakeup AP
callback") changed the signature of struct apic::wakeup_secondary_cpu(),
but it did not update numachip_wakeup_secondary().  Update it to fix the
compile error.

arch/x86/kernel/apic/apic_numachip.c:228:43: error: initialization of 'int (*)(u32,  long unsigned int,  unsigned int)' {aka 'int (*)(unsigned int,  long unsigned int,  unsigned int)'} from incompatible pointer type 'int (*)(u32,  long unsigned int)' {aka 'int (*)(unsigned int,  long unsigned int)'} [-Wincompatible-pointer-types]
  228 |         .wakeup_secondary_cpu           = numachip_wakeup_secondary,
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~

Fixes: df21bf37518b ("arch/x86: Provide the CPU number in the wakeup AP callback")
Signed-off-by: Isaku Yamahata <isaku.yamahata@intel.com>